### ISSUE TITLE
RTL issue

### ISSUE THREAD

**Issue by Benyamin001** [sakhnyuk/rc-scrollbars#12]
Hi
in RTL page vertical scroll bar appear in left side of elements and its visible when use rc-scrollbars in version 1.0.0 the main div have scrollBar class name and with this class , I fix this issue in my project but in version 1.0.3 scrollBar  class removed and all scroll bar visible again

**Comment by Tomassito** [comment]
Hi @Benyamin001,  we have already discussed briefly with @sakhnyuk an improvement that would let you pass classnames for any of the subcomponents. You can expect a PR this week and live changes as soon as it gets reviewed.

**Comment by sakhnyuk** [comment]
@Benyamin001 
Yes, I've removed the "scrollView" className, because it doesn't use in the project anymore. But you can add your custom className by passing renderView prop.

```jsx
      <Scrollbars renderView={props => <div {...props} className="scrollView"/>}>
        {children}
      </Scrollbars>
```

As said @Tomassito, in future updates, we have plans to add special props for classnames.

Also, I think about the RTL support feature. This is an important option too.

**Comment by Tomassito** [comment]
@Benyamin001 Could you confirm that you could handle your issue with the solution proposed?

**Comment by Benyamin001** [comment]
it's working, thanks

**Comment by paymanzafar1** [comment]
Hi @sakhnyuk.

RTL language support is a required feature. I am using Rocket.Chat software that uses this component. All the horizontal scrollbars do not work, and the vertical ones have margin problem.

Please add this feature as soon as possible. Thank you.
